# Generated by Django 4.1.7 on 2023-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0002_alter_consulta_data_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQVCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qvc31', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc32', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc33', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc34', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc35', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc36', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc37', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc38', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc39', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc40', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc41', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc42', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc43', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc44', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc45', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc46', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc47', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc48', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc49', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc50', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc51', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc52', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc53', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('qvc54', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
            ],
        ),
    ]
