# Generated by Django 4.1.7 on 2023-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0002_alter_consulta_data_consulta'),
        ('respostatexto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAICS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aics01', models.DateField(verbose_name='Data de nascimento')),
                ('aics03', models.FloatField(verbose_name='Peso')),
                ('aics04', models.FloatField(verbose_name='Altura')),
                ('aics05', models.CharField(choices=[('Soberest', 'Soberest'), ('Obesidade grau I', 'Obesidade grau I'), ('Obesidade grau II', 'Obesidade grau II'), ('Obesidade grau III', 'Obesidade grau III')], max_length=20, verbose_name='IMC')),
                ('aics06', models.FloatField(verbose_name='Circunferência abdominal')),
                ('aics07', models.IntegerField(verbose_name='Paridade (gestações)')),
                ('aics08', models.IntegerField(verbose_name='Paridade (partos)')),
                ('aics09', models.IntegerField(verbose_name='Paridade (abortos)')),
                ('aics10', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Menopausa por tratamento oncológico')),
                ('aics12', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Tabagista')),
                ('aics13', models.DateField(null=True, verbose_name='Ex-tabagista (há quanto tempo)')),
                ('aics14', models.CharField(choices=[('Preta', 'Preta'), ('Parda', 'Parda'), ('Branca', 'Branca'), ('Indígena', 'Indígena'), ('Amarela', 'Amarela')], max_length=20, verbose_name='Cor da pele')),
                ('aics15', models.CharField(choices=[('Casada/União estável', 'Casada/União estável'), ('Solteira', 'Solteira'), ('Divorciada/Separada', 'Divorciada/Separada'), ('Viúva', 'Viúva')], max_length=20, verbose_name='Estado civil')),
                ('aics16', models.CharField(choices=[('Do lar', 'Do lar'), ('Em atividade ', 'Em atividade'), ('Aposentada', 'Aposentada'), ('Desempregada', 'Desempregada')], max_length=20, verbose_name='Profissão')),
                ('aics17', models.CharField(choices=[('Analfabeta', 'Analfabeta'), ('Fundamental incompleto', 'Fundamental incompleto'), ('Fundamental completo', 'Fundamental completo'), ('Ensino médio incompleto', 'Ensino médio incompleto'), ('Ensino médio completo', 'Ensino médio completo'), ('Superior incompleto', 'Superior incompleto'), ('Superior completo', 'Superior completo'), ('Pós-graduação', 'Pós-graduação')], max_length=50, verbose_name='Escolaridade')),
                ('aics18', models.CharField(choices=[('Menor que 1 salário', 'Menor que 1 salário'), ('Entre 1 e 3 salário(s)', 'Entre 1 e 3 salário(s)'), ('Maior que 3 salários', 'Maior que 3 salários'), ('Sem renda', 'Sem renda'), ('Sem informação', 'Sem informação')], max_length=50, verbose_name='Renda familiar')),
                ('aics19', models.CharField(choices=[('Não possui', 'Não possui'), ('Aposentada', 'Aposentada'), ('Beneficiária', 'Beneficiária')], max_length=20, verbose_name='Vínculo previdenciário')),
                ('aics20', models.CharField(choices=[('0', '0'), ('I A', 'I A'), ('I B', 'I B'), ('II A', 'II A'), ('II B', 'II B'), ('III A', 'III A'), ('III B', 'III B'), ('I V', 'I V'), ('Sem informação', 'Sem informação')], max_length=20, verbose_name='Estadiamento Clínico FIGO')),
                ('aics21', models.CharField(choices=[('Carcinoma epidermóide', 'Carcinoma epidermóide'), ('Adenocarcinoma', 'Adenocarcinoma'), ('Outros', 'Outros'), ('Sem informação', 'Sem informação')], max_length=50, verbose_name='Estadiamento histopatológico')),
                ('aics22', models.CharField(choices=[('Grau X', 'Grau X'), ('Grau 1', 'Grau 1'), ('Grau 2', 'Grau 2'), ('Grau 3', 'Grau 3'), ('Sem informação', 'Sem informação')], max_length=20, verbose_name='Tipo/grau histológico')),
                ('aics24', models.CharField(max_length=20, null=True, verbose_name='Procedimento cirúrgico')),
                ('aics25', models.DateField(null=True, verbose_name='Data de realização da primeira cirurgia:')),
                ('aics26', models.CharField(choices=[('HTA I', 'HTA I'), ('HTA II', 'HTA II'), ('HTA III', 'HTA III'), ('HTV', 'HTV'), ('SOB', 'SOB'), ('SOU/SOD/SOE', 'SOU/SOD/SOE'), ('Traquelectomia radical', 'Traquelectomia radical'), ('Cirurgia de Schauta', 'Cirurgia de Schauta')], max_length=50, null=True, verbose_name='Técnica cirúrgica')),
                ('aics27', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Sem informação', 'Sem informação')], max_length=20, null=True, verbose_name='Complicação pós-cirúrgica até 30 dias após a cirurgia')),
                ('aics28', models.IntegerField(null=True, verbose_name='Número de sessões de radioterapia')),
                ('aics29', models.FloatField(null=True, verbose_name='Dose na radioterapia (Gy)')),
                ('aics30', models.DateField(null=True, verbose_name='Tempo de tratamento com radioterapia')),
                ('aics31', models.IntegerField(null=True, verbose_name='Número de sessões de braquiterapia:')),
                ('aics32', models.FloatField(null=True, verbose_name='Dose na braquiterapia (Gy)')),
                ('aics33', models.DateField(null=True, verbose_name='Tempo de tratamento com braquiterapia')),
                ('aics34', models.CharField(choices=[('Neoadjuvante', 'Neoadjuvante'), ('Adjuvante', 'Adjuvante')], max_length=20, null=True, verbose_name='Tipo da quimioterapia')),
                ('aics11', models.ManyToManyField(related_name='+', to='respostatexto.respostatexto', verbose_name='Sintomas da menopausa')),
                ('aics23', models.ManyToManyField(related_name='+', to='respostatexto.respostatexto', verbose_name='Tratamento indicado')),
                ('aics35', models.ManyToManyField(null=True, related_name='+', to='respostatexto.respostatexto', verbose_name='Comorbidades')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_aics', to='consulta.consulta')),
            ],
        ),
    ]
