# Generated by Django 4.1.7 on 2023-03-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formFIQL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfiql',
            name='fiql01',
            field=models.CharField(choices=[('Muito boa', 'Muito boa'), ('Boa', 'Boa'), ('Regular', 'Regular'), ('Ruim', 'Ruim')], max_length=70, verbose_name='Em geral você diria que sua saúde é'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql02',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Tenho medo de sair'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql03',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Evito visitar amigos ou parentes'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql04',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Evito passar a noite longe de casa'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql05',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='É difícil para eu sair e fazer coisas como ir ao cinema ou à igreja'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql06',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Evito comer antes de sair de casa'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql07',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Quando estou fora de casa tento ficar sempre que possível próximo ao banheiro'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql08',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='É importante eu planejar o que vou fazer de acordo com o meu funcionamento intestinal'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql09',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Evito viajar'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql10',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Fico preocupado em não ser capaz de chegar ao banheiro em tempo'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql11',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Sinto que não tenho controle do meu intestino'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql12',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Não consigo controlar minha evacuação a tempo de chegar ao banheiro'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql13',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Perco fezes sem perceber'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql14',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Tento evitar a perda de fezes, ficando próximo ao banheiro'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql15',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Fico envergonhado'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql16',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Não posso fazer muitas coisas que eu quero fazer'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql17',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Fico preocupado em perder fezes'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql18',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Sinto-me deprimido'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql19',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Fico preocupado se outras pessoas sentem cheiro de fezes em mim'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql20',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Acho que não sou uma pessoa saudável'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql21',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Tenho menos prazer em viver'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql22',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Tenho uma relação sexual com menor frequência do que gostaria'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql23',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Sinto-me diferente das outras pessoas'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql24',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Sempre estou pensando na possibilidade de perder fezes'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql25',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Tenho medo de ter sexo'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql26',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Evito viajar de carro ou ônibus'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql27',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Evito sair para comer'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql28',
            field=models.CharField(choices=[('Muitas vezes', 'Muitas vezes'), ('Algumas vezes', 'Algumas vezes'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez'), ('Nenhuma das respostas', 'Nenhuma das respostas')], max_length=70, verbose_name='Quando vou a um lugar novo, procuro saber onde está o banheiro'),
        ),
        migrations.AlterField(
            model_name='formfiql',
            name='fiql29',
            field=models.CharField(choices=[('Extremamente. A ponto de desistir', 'Extremamente. A ponto de desistir'), ('Muitas vezes', 'Muitas vezes'), ('Com frequência', 'Com frequência'), ('Algumas vezes - o suficiente para me preocupar (incomodar)', 'Algumas vezes - o suficiente para me preocupar (incomodar)'), ('Poucas vezes', 'Poucas vezes'), ('Nenhuma vez', 'Nenhuma vez')], max_length=70, verbose_name='Durante o mês passado, eu me senti tão triste, desanimado ou tive muitos problemas que me fizeram pensar que nada valia a pena'),
        ),
    ]
