# Generated by Django 4.1.7 on 2023-03-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qvc01', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc02', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc03', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc04', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc05', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc06', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc07', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc08', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc09', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc10', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc11', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc12', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc13', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc14', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc15', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc16', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc17', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc18', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc19', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc20', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc21', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc22', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc23', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc24', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc25', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc26', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc27', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc28', models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1)),
                ('qvc29', models.CharField(choices=[('1', 'pessima'), ('2', 'muito ruim'), ('3', 'ruim'), ('4', 'moderado'), ('5', 'bom'), ('6', 'muito bom'), ('7', 'otima')], max_length=1)),
                ('qvc30', models.CharField(choices=[('1', 'pessima'), ('2', 'muito ruim'), ('3', 'ruim'), ('4', 'moderado'), ('5', 'bom'), ('6', 'muito bom'), ('7', 'otima')], max_length=1)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
            ],
        ),
    ]
