# Generated by Django 4.1.7 on 2023-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formQVC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formqvc',
            name='qvc01',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Voce tem qualquer dificuldade quando faz grandes esforços (carregar bolsa de compras pesada ou mala?)'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc02',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem dificuldade quando faz grande caminhada?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc03',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem qualquer dificuldade quando faz uma curta caminhada fora de casa?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc04',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem que ficar numa cama ou cadeira durante o dia?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc05',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você precisa de ajuda para se alimentar, se vestir, se lavar ou usar o banheiro?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc06',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Tem sido difícil trabalhar ou realizar suas atividades diárias?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc07',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Tem sido difícil praticar seu hobby ou participar de atividades de lazer?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc08',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você teve falta de ar?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc09',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem tido dor?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc10',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você precisou repousar?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc11',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem tido problemas para dormir?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc12',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem se sentido fraca?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc13',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem sentido falta de apetite?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc14',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem se sentido enjoada?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc15',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem vomitado?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc16',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem tido prisão de ventre?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc17',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem diarréia?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc18',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você esteve cansada?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc19',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='A dor interferiu em suas atividades diárias?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc20',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem tido dificuldade para se concentrar em coisas, como ler jornal ou ver televisão?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc21',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você se sentiu nervosa?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc22',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você esteve preocupada?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc23',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você se sentiu irritada facilmente?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc24',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você se sentiu deprimida?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc25',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='Você tem tido dificuldade de se lembrar das coisas?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc26',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='A sua condição física ou o tratamento médico tem interferido em sua atividade familiar?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc27',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='A sua condição física ou o tratamento médico tem interferido em suas atividades sociais?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc28',
            field=models.CharField(choices=[('1', 'nao'), ('2', 'pouco'), ('3', 'moderado'), ('4', 'muito')], max_length=1, verbose_name='A sua condição física ou o tratamento médico tem lhe trazido dificuldades financeiras?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc29',
            field=models.CharField(choices=[('1', 'pessima'), ('2', 'muito ruim'), ('3', 'ruim'), ('4', 'moderado'), ('5', 'bom'), ('6', 'muito bom'), ('7', 'otima')], max_length=1, verbose_name='Como você classifica a sua saúde em geral, durante a última semana?'),
        ),
        migrations.AlterField(
            model_name='formqvc',
            name='qvc30',
            field=models.CharField(choices=[('1', 'pessima'), ('2', 'muito ruim'), ('3', 'ruim'), ('4', 'moderado'), ('5', 'bom'), ('6', 'muito bom'), ('7', 'otima')], max_length=1, verbose_name='Como você classifica a sua qualidade de vida em geral durante a última semana?'),
        ),
    ]
