# Generated by Django 4.1.7 on 2023-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0002_alter_consulta_data_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAGPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agpg01', models.FloatField(verbose_name='Peso')),
                ('agpg02', models.FloatField(verbose_name='Altura')),
                ('agpg03', models.CharField(choices=[('Soberest', 'Soberest'), ('Obesidade grau I', 'Obesidade grau I'), ('Obesidade grau II', 'Obesidade grau II'), ('Obesidade grau III', 'Obesidade grau III')], max_length=20, verbose_name='IMC')),
                ('agpg04', models.FloatField(verbose_name='Circunferência abdominal')),
                ('agpg05', models.FloatField(max_length=10, verbose_name='MID 21')),
                ('agpg06', models.FloatField(max_length=10, verbose_name='MID 14')),
                ('agpg07', models.FloatField(max_length=10, verbose_name='MID 07')),
                ('agpg08', models.FloatField(max_length=10, verbose_name='MID BSP')),
                ('agpg09', models.FloatField(max_length=10, verbose_name='MID 28')),
                ('agpg10', models.FloatField(max_length=10, verbose_name='MID 35')),
                ('agpg11', models.FloatField(max_length=10, verbose_name='MID TT')),
                ('agpg12', models.FloatField(max_length=10, verbose_name='MID Pé')),
                ('agpg13', models.FloatField(max_length=10, verbose_name='MIE 21')),
                ('agpg14', models.FloatField(max_length=10, verbose_name='MIE 14')),
                ('agpg15', models.FloatField(max_length=10, verbose_name='MIE 07')),
                ('agpg16', models.FloatField(max_length=10, verbose_name='MIE BSP')),
                ('agpg17', models.FloatField(max_length=10, verbose_name='MIE 28')),
                ('agpg18', models.FloatField(max_length=10, verbose_name='MIE 35')),
                ('agpg19', models.FloatField(max_length=10, verbose_name='MIE TT')),
                ('agpg20', models.FloatField(max_length=10, verbose_name='MIE Pé')),
                ('agpg21', models.FloatField(max_length=10, verbose_name='# 21')),
                ('agpg22', models.FloatField(max_length=10, verbose_name='# 14')),
                ('agpg23', models.FloatField(max_length=10, verbose_name='# 07')),
                ('agpg24', models.FloatField(max_length=10, verbose_name='# BSP')),
                ('agpg25', models.FloatField(max_length=10, verbose_name='# 28')),
                ('agpg26', models.FloatField(max_length=10, verbose_name='# 35')),
                ('agpg27', models.FloatField(max_length=10, verbose_name='# TT')),
                ('agpg28', models.FloatField(max_length=10, verbose_name='# Pé')),
                ('agpg29', models.CharField(choices=[('Sem alterações', 'Sem alterações'), ('Sintomático reversível com elevação do membro', 'Sintomático reversível com elevação do membro'), ('Com alteração objetiva cutânea', 'Com alteração objetiva cutânea'), ('Aguda', 'Aguda'), ('Tardia (com fibrose)', 'Tardia (com fibrose)'), ('Elefantíase', 'Elefantíase')], max_length=50, verbose_name='Resultado')),
                ('agpg30', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Sensação de peso')),
                ('agpg31', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Pele esticada ')),
                ('agpg32', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Formigamento')),
                ('agpg33', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Sensação de perna dura/movimentos reduzidos')),
                ('agpg34', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Alguma dificuldade para realizar atividade física')),
                ('agpg35', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Mudança de coloração')),
                ('agpg36', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Telangiectasias')),
                ('agpg37', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Veias varicosas')),
                ('agpg38', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Úlcera venosa')),
                ('agpg39', models.CharField(choices=[('Fechada', 'Fechada'), ('Aberta', 'Aberta')], max_length=20, null=True, verbose_name='Tipo úlcera venosa')),
                ('agpg40', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Lesão nervosa periférica')),
                ('agpg41', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4 ', '4 '), ('5 ', '5 ')], verbose_name='Flexão do quadril direito')),
                ('agpg42', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4 ', '4 '), ('5 ', '5 ')], verbose_name='Flexão do quadril esquerdo')),
                ('agpg43', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4 ', '4 '), ('5 ', '5 ')], verbose_name='Extensão do joelho direito')),
                ('agpg44', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4 ', '4 '), ('5 ', '5 ')], verbose_name='Extensão do joelho esquerdo')),
                ('agpg45', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4 ', '4 '), ('5 ', '5 ')], verbose_name='Dorsiflexão do tornozelo direito')),
                ('agpg46', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4 ', '4 '), ('5 ', '5 ')], verbose_name='Dorsiflexão do tornozelo esquerdo')),
                ('agpg47', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Alterações da função intestinal')),
                ('agpg48', models.CharField(choices=[('Tipo I', 'Tipo I'), ('Tipo II', 'Tipo II'), ('Tipo III', 'Tipo III'), ('Tipo IV', 'Tipo IV'), ('Tipo V', 'Tipo V')], max_length=20, verbose_name='Escala de Bristol')),
                ('agpg49', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Incontinência')),
                ('agpg50', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Alterações da função vesical')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_agpg', to='consulta.consulta')),
            ],
        ),
    ]
