# Generated by Django 4.1.7 on 2023-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0002_alter_consulta_data_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormKHQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khq01', models.CharField(choices=[('1', 'muito bom'), ('2', 'bom'), ('3', 'regular'), ('4', 'mau'), ('5', 'muito mau')], max_length=1, verbose_name='')),
                ('khq02', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq03a', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq03b', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq04a', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq04b', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq04c', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq04d', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq05a', models.CharField(choices=[('1', 'nao aplicavel'), ('2', 'nada'), ('3', 'um pouco'), ('4', 'moderadamente'), ('5', 'muito')], max_length=1, verbose_name='')),
                ('khq05b', models.CharField(choices=[('1', 'nao aplicavel'), ('2', 'nada'), ('3', 'um pouco'), ('4', 'moderadamente'), ('5', 'muito')], max_length=1, verbose_name='')),
                ('khq05c', models.CharField(choices=[('1', 'nao aplicavel'), ('2', 'nada'), ('3', 'um pouco'), ('4', 'moderadamente'), ('5', 'muito')], max_length=1, verbose_name='')),
                ('khq06a', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq06b', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq06c', models.CharField(choices=[('1', 'nada'), ('2', 'um pouco'), ('3', 'moderadamente'), ('4', 'muito')], max_length=1, verbose_name='')),
                ('khq07a', models.CharField(choices=[('1', 'nunca'), ('2', 'as vezes'), ('3', 'frequentemente'), ('4', 'sempre')], max_length=1, verbose_name='')),
                ('khq07b', models.CharField(choices=[('1', 'nunca'), ('2', 'as vezes'), ('3', 'frequentemente'), ('4', 'sempre')], max_length=1, verbose_name='')),
                ('khq08a', models.CharField(choices=[('1', 'nunca'), ('2', 'as vezes'), ('3', 'frequentemente'), ('4', 'sempre')], max_length=1, verbose_name='')),
                ('khq08b', models.CharField(choices=[('1', 'nunca'), ('2', 'as vezes'), ('3', 'frequentemente'), ('4', 'sempre')], max_length=1, verbose_name='')),
                ('khq08c', models.CharField(choices=[('1', 'nunca'), ('2', 'as vezes'), ('3', 'frequentemente'), ('4', 'sempre')], max_length=1, verbose_name='')),
                ('khq08d', models.CharField(choices=[('1', 'nunca'), ('2', 'as vezes'), ('3', 'frequentemente'), ('4', 'sempre')], max_length=1, verbose_name='')),
                ('khq08e', models.CharField(choices=[('1', 'nunca'), ('2', 'as vezes'), ('3', 'frequentemente'), ('4', 'sempre')], max_length=1, verbose_name='')),
                ('consulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
            ],
        ),
    ]
