# Generated by Django 4.1.7 on 2023-03-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
        ('formKHQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formkhq',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta'),
        ),
    ]
