# Generated by Django 4.1.7 on 2023-04-01 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_consulta_data_consulta'),
        ('formKHQ', '0002_formkhq_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formkhq',
            name='consulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta'),
        ),
    ]
